/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createProblemDetailsFromDiscriminatorValue, createStringDuplicateFromDiscriminatorValue, deserializeIntoProblemDetails, Generation, ObjectGCStatus, serializeProblemDetails, type ProblemDetails, type StringDuplicate } from '../../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

export interface StringDuplicatesRequestBuilderGetQueryParameters {
    gcStatus?: ObjectGCStatus;
    generation?: Generation;
}
/**
 * Builds and executes requests for operations under /api/dump/string-duplicates
 */
export class StringDuplicatesRequestBuilder extends BaseRequestBuilder<StringDuplicatesRequestBuilder> {
    /**
     * Instantiates a new StringDuplicatesRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/string-duplicates{?gcStatus*,generation*}", (x, y) => new StringDuplicatesRequestBuilder(x, y));
    }
    /**
     * Get string duplicates
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of StringDuplicate
     */
    public get(requestConfiguration?: RequestConfiguration<StringDuplicatesRequestBuilderGetQueryParameters> | undefined) : Promise<StringDuplicate[] | undefined> {
        const requestInfo = this.toGetRequestInformation(
            requestConfiguration
        );
        const errorMapping = {
            "500": createProblemDetailsFromDiscriminatorValue,
        } as Record<string, ParsableFactory<Parsable>>;
        return this.requestAdapter.sendCollectionAsync<StringDuplicate>(requestInfo, createStringDuplicateFromDiscriminatorValue, errorMapping);
    }
    /**
     * Get string duplicates
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(requestConfiguration?: RequestConfiguration<StringDuplicatesRequestBuilderGetQueryParameters> | undefined) : RequestInformation {
        const requestInfo = new RequestInformation(HttpMethod.GET, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        return requestInfo;
    }
}
/* tslint:enable */
/* eslint-enable */
