/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createObjectTypeStatisticsFromDiscriminatorValue, TraversingHeapModes, type ObjectTypeStatistics } from '../../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

export interface TypeStatisticsRequestBuilderGetQueryParameters {
    traversingMode?: TraversingHeapModes;
}
/**
 * Builds and executes requests for operations under /api/dump/type-statistics
 */
export class TypeStatisticsRequestBuilder extends BaseRequestBuilder<TypeStatisticsRequestBuilder> {
    /**
     * Instantiates a new TypeStatisticsRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/type-statistics{?traversingMode*}", (x, y) => new TypeStatisticsRequestBuilder(x, y));
    }
    /**
     * Get type statistics
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ObjectTypeStatistics
     */
    public get(requestConfiguration?: RequestConfiguration<TypeStatisticsRequestBuilderGetQueryParameters> | undefined) : Promise<ObjectTypeStatistics[] | undefined> {
        const requestInfo = this.toGetRequestInformation(
            requestConfiguration
        );
        return this.requestAdapter.sendCollectionAsync<ObjectTypeStatistics>(requestInfo, createObjectTypeStatisticsFromDiscriminatorValue, undefined);
    }
    /**
     * Get type statistics
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(requestConfiguration?: RequestConfiguration<TypeStatisticsRequestBuilderGetQueryParameters> | undefined) : RequestInformation {
        const requestInfo = new RequestInformation(HttpMethod.GET, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        return requestInfo;
    }
}
/* tslint:enable */
/* eslint-enable */
