/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { ClrRootKind, createProblemDetailsFromDiscriminatorValue, createRootInfoFromDiscriminatorValue, deserializeIntoProblemDetails, serializeProblemDetails, type ProblemDetails, type RootInfo } from '../../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

export interface RootsRequestBuilderGetQueryParameters {
    kind?: ClrRootKind;
}
/**
 * Builds and executes requests for operations under /api/dump/roots
 */
export class RootsRequestBuilder extends BaseRequestBuilder<RootsRequestBuilder> {
    /**
     * Instantiates a new RootsRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/roots{?kind*}", (x, y) => new RootsRequestBuilder(x, y));
    }
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of RootInfo
     */
    public get(requestConfiguration?: RequestConfiguration<RootsRequestBuilderGetQueryParameters> | undefined) : Promise<RootInfo[] | undefined> {
        const requestInfo = this.toGetRequestInformation(
            requestConfiguration
        );
        const errorMapping = {
            "500": createProblemDetailsFromDiscriminatorValue,
        } as Record<string, ParsableFactory<Parsable>>;
        return this.requestAdapter.sendCollectionAsync<RootInfo>(requestInfo, createRootInfoFromDiscriminatorValue, errorMapping);
    }
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(requestConfiguration?: RequestConfiguration<RootsRequestBuilderGetQueryParameters> | undefined) : RequestInformation {
        const requestInfo = new RequestInformation(HttpMethod.GET, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        return requestInfo;
    }
}
/* tslint:enable */
/* eslint-enable */
