/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createHttpRequestInfoFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, deserializeIntoProblemDetails, HttpRequestStatus, ObjectGCStatus, serializeProblemDetails, type HttpRequestInfo, type ProblemDetails } from '../../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

export interface HttpRequestsRequestBuilderGetQueryParameters {
    gcStatus?: ObjectGCStatus;
    status?: HttpRequestStatus;
}
/**
 * Builds and executes requests for operations under /api/dump/http-requests
 */
export class HttpRequestsRequestBuilder extends BaseRequestBuilder<HttpRequestsRequestBuilder> {
    /**
     * Instantiates a new HttpRequestsRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/http-requests{?gcStatus*,status*}", (x, y) => new HttpRequestsRequestBuilder(x, y));
    }
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of HttpRequestInfo
     */
    public get(requestConfiguration?: RequestConfiguration<HttpRequestsRequestBuilderGetQueryParameters> | undefined) : Promise<HttpRequestInfo[] | undefined> {
        const requestInfo = this.toGetRequestInformation(
            requestConfiguration
        );
        const errorMapping = {
            "500": createProblemDetailsFromDiscriminatorValue,
        } as Record<string, ParsableFactory<Parsable>>;
        return this.requestAdapter.sendCollectionAsync<HttpRequestInfo>(requestInfo, createHttpRequestInfoFromDiscriminatorValue, errorMapping);
    }
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(requestConfiguration?: RequestConfiguration<HttpRequestsRequestBuilderGetQueryParameters> | undefined) : RequestInformation {
        const requestInfo = new RequestInformation(HttpMethod.GET, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        return requestInfo;
    }
}
/* tslint:enable */
/* eslint-enable */
