/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createProblemDetailsFromDiscriminatorValue, createSparseArrayStatisticsFromDiscriminatorValue, deserializeIntoProblemDetails, Generation, serializeProblemDetails, TraversingHeapModes, type ProblemDetails, type SparseArrayStatistics } from '../../../../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

export interface StatRequestBuilderGetQueryParameters {
    generation?: Generation;
    traversingMode?: TraversingHeapModes;
}
/**
 * Builds and executes requests for operations under /api/dump/arrays/sparse/stat
 */
export class StatRequestBuilder extends BaseRequestBuilder<StatRequestBuilder> {
    /**
     * Instantiates a new StatRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/arrays/sparse/stat{?traversingMode*,generation*}", (x, y) => new StatRequestBuilder(x, y));
    }
    /**
     * Get arrays
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of SparseArrayStatistics
     */
    public get(requestConfiguration?: RequestConfiguration<StatRequestBuilderGetQueryParameters> | undefined) : Promise<SparseArrayStatistics[] | undefined> {
        const requestInfo = this.toGetRequestInformation(
            requestConfiguration
        );
        const errorMapping = {
            "500": createProblemDetailsFromDiscriminatorValue,
        } as Record<string, ParsableFactory<Parsable>>;
        return this.requestAdapter.sendCollectionAsync<SparseArrayStatistics>(requestInfo, createSparseArrayStatisticsFromDiscriminatorValue, errorMapping);
    }
    /**
     * Get arrays
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(requestConfiguration?: RequestConfiguration<StatRequestBuilderGetQueryParameters> | undefined) : RequestInformation {
        const requestInfo = new RequestInformation(HttpMethod.GET, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        return requestInfo;
    }
}
/* tslint:enable */
/* eslint-enable */
