/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { SparseRequestBuilder } from './sparse/';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/dump/arrays
 */
export class ArraysRequestBuilder extends BaseRequestBuilder<ArraysRequestBuilder> {
    /**
     * The sparse property
     */
    public get sparse(): SparseRequestBuilder {
        return new SparseRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new ArraysRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/arrays", (x, y) => new ArraysRequestBuilder(x, y));
    }
}
/* tslint:enable */
/* eslint-enable */
