openapi: 3.0.1
info:
  title: Heartbeat
  description: Heartbeat contract
  contact:
    name: Heartbeat
  version: 0.1.0
servers:
  - url: /
paths:
  /api/dump/info:
    get:
      tags:
        - Dump
      summary: Get dump info
      operationId: GetInfo
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DumpInfo'
  /api/dump/modules:
    get:
      tags:
        - Dump
      summary: Get modules
      operationId: GetModules
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'
  /api/dump/segments:
    get:
      tags:
        - Dump
      summary: Get segments
      operationId: GetSegments
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HeapSegment'
  /api/dump/roots:
    get:
      tags:
        - Dump
      summary: Get heap roots
      operationId: GetRoots
      parameters:
        - name: kind
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ClrRootKind'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RootInfo'
  /api/dump/heap-dump-statistics:
    get:
      tags:
        - Dump
      summary: Get heap dump statistics
      operationId: GetHeapDumpStat
      parameters:
        - name: gcStatus
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ObjectGCStatus'
        - name: generation
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/Generation'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ObjectTypeStatistics'
  /api/dump/strings:
    get:
      tags:
        - Dump
      summary: Get heap dump statistics
      operationId: GetStrings
      parameters:
        - name: gcStatus
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ObjectGCStatus'
        - name: generation
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/Generation'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StringInfo'
  /api/dump/string-duplicates:
    get:
      tags:
        - Dump
      summary: Get string duplicates
      operationId: GetStringDuplicates
      parameters:
        - name: gcStatus
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ObjectGCStatus'
        - name: generation
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/Generation'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StringDuplicate'
  '/api/dump/object-instances/{mt}':
    get:
      tags:
        - Dump
      summary: Get object instances
      operationId: GetObjectInstances
      parameters:
        - name: mt
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int64
        - name: gcStatus
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ObjectGCStatus'
        - name: generation
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/Generation'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetObjectInstancesResult'
  /api/dump/arrays/sparse:
    get:
      tags:
        - Dump
      summary: Get sparse arrays
      operationId: GetSparseArrays
      parameters:
        - name: gcStatus
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ObjectGCStatus'
        - name: generation
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/Generation'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArrayInfo'
  /api/dump/arrays/sparse/stat:
    get:
      tags:
        - Dump
      summary: Get arrays
      operationId: GetSparseArraysStat
      parameters:
        - name: gcStatus
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/ObjectGCStatus'
        - name: generation
          in: query
          style: form
          schema:
            $ref: '#/components/schemas/Generation'
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SparseArrayStatistics'
  '/api/dump/object/{address}':
    get:
      tags:
        - Dump
      summary: Get object
      operationId: GetClrObject
      parameters:
        - name: address
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int64
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClrObjectResult'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/api/dump/object/{address}/roots':
    get:
      tags:
        - Dump
      summary: Get object roots
      operationId: GetClrObjectRoots
      parameters:
        - name: address
          in: path
          required: true
          style: simple
          schema:
            type: integer
            format: int64
      responses:
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ClrObjectRootPath'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  schemas:
    Architecture:
      enum:
        - X86
        - X64
        - Arm
        - Arm64
        - Wasm
        - S390x
        - LoongArch64
        - Armv6
        - Ppc64le
      type: string
    ArrayInfo:
      required:
        - address
        - length
        - methodTable
        - unusedItemsCount
        - unusedPercent
        - wasted
      type: object
      properties:
        address:
          type: integer
          format: int64
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
          nullable: true
        length:
          type: integer
          format: int32
        unusedItemsCount:
          type: integer
          format: int32
        unusedPercent:
          type: number
          format: double
        wasted:
          type: integer
          format: int64
      additionalProperties: false
    ClrObjectField:
      required:
        - isValueType
        - methodTable
        - name
        - offset
        - value
      type: object
      properties:
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
          nullable: true
        offset:
          type: integer
          format: int32
        isValueType:
          type: boolean
        objectAddress:
          type: integer
          format: int64
          nullable: true
        value:
          type: string
        name:
          type: string
      additionalProperties: false
    ClrObjectRootPath:
      required:
        - pathItems
        - root
      type: object
      properties:
        root:
          $ref: '#/components/schemas/RootInfo'
        pathItems:
          type: array
          items:
            $ref: '#/components/schemas/RootPathItem'
      additionalProperties: false
    ClrRootKind:
      enum:
        - None
        - FinalizerQueue
        - StrongHandle
        - PinnedHandle
        - Stack
        - RefCountedHandle
        - AsyncPinnedHandle
        - SizedRefHandle
      type: string
    DumpInfo:
      required:
        - architecture
        - canWalkHeap
        - clrModulePath
        - dumpPath
        - isServerHeap
        - platform
        - processId
        - runtimeVersion
      type: object
      properties:
        dumpPath:
          type: string
        canWalkHeap:
          type: boolean
        isServerHeap:
          type: boolean
        clrModulePath:
          type: string
        architecture:
          $ref: '#/components/schemas/Architecture'
        processId:
          type: integer
          format: int32
        platform:
          type: string
        runtimeVersion:
          type: string
      additionalProperties: false
    GCSegmentKind:
      enum:
        - Generation0
        - Generation1
        - Generation2
        - Large
        - Pinned
        - Frozen
        - Ephemeral
      type: string
    Generation:
      enum:
        - Generation0
        - Generation1
        - Generation2
        - Large
        - Pinned
        - Frozen
        - Unknown
      type: string
    GetClrObjectResult:
      required:
        - address
        - fields
        - generation
        - methodTable
        - size
      type: object
      properties:
        address:
          type: integer
          format: int64
        moduleName:
          type: string
          nullable: true
        typeName:
          type: string
          nullable: true
        methodTable:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        generation:
          $ref: '#/components/schemas/Generation'
        value:
          type: string
          nullable: true
        fields:
          type: array
          items:
            $ref: '#/components/schemas/ClrObjectField'
      additionalProperties: false
    GetObjectInstancesResult:
      required:
        - instances
        - methodTable
      type: object
      properties:
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
          nullable: true
        instances:
          type: array
          items:
            $ref: '#/components/schemas/ObjectInstance'
      additionalProperties: false
    HeapSegment:
      required:
        - end
        - kind
        - size
        - start
      type: object
      properties:
        start:
          type: integer
          format: int64
        end:
          type: integer
          format: int64
        kind:
          $ref: '#/components/schemas/GCSegmentKind'
        size:
          type: integer
          format: int64
          readOnly: true
      additionalProperties: false
    Module:
      required:
        - address
        - size
      type: object
      properties:
        address:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
      additionalProperties: false
    ObjectGCStatus:
      enum:
        - Live
        - Dead
      type: string
    ObjectInstance:
      required:
        - address
        - size
      type: object
      properties:
        address:
          type: integer
          format: int64
        size:
          type: integer
          format: int64
      additionalProperties: false
    ObjectTypeStatistics:
      required:
        - instanceCount
        - methodTable
        - totalSize
        - typeName
      type: object
      properties:
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
        totalSize:
          type: integer
          format: int64
        instanceCount:
          type: integer
          format: int32
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
    RootInfo:
      required:
        - address
        - isPinned
        - kind
        - methodTable
        - size
        - typeName
      type: object
      properties:
        address:
          type: integer
          format: int64
        kind:
          $ref: '#/components/schemas/ClrRootKind'
        isPinned:
          type: boolean
        size:
          type: integer
          format: int64
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
      additionalProperties: false
    RootPathItem:
      required:
        - address
        - generation
        - methodTable
        - size
      type: object
      properties:
        address:
          type: integer
          format: int64
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
          nullable: true
        size:
          type: integer
          format: int64
        generation:
          $ref: '#/components/schemas/Generation'
      additionalProperties: false
    SparseArrayStatistics:
      required:
        - count
        - methodTable
        - totalWasted
      type: object
      properties:
        methodTable:
          type: integer
          format: int64
        typeName:
          type: string
          nullable: true
        count:
          type: integer
          format: int32
        totalWasted:
          type: integer
          format: int64
      additionalProperties: false
    StringDuplicate:
      required:
        - count
        - fullLength
        - value
        - wastedMemory
      type: object
      properties:
        value:
          type: string
        count:
          type: integer
          format: int32
        fullLength:
          type: integer
          format: int32
        wastedMemory:
          type: integer
          format: int64
      additionalProperties: false
    StringInfo:
      required:
        - address
        - length
        - size
        - value
      type: object
      properties:
        address:
          type: integer
          format: int64
        length:
          type: integer
          format: int32
        size:
          type: integer
          format: int64
        value:
          type: string
      additionalProperties: false