/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { WithMtItemRequestBuilder } from './item/';
import { BaseRequestBuilder, getPathParameters, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/dump/object-instances
 */
export class ObjectInstancesRequestBuilder extends BaseRequestBuilder<ObjectInstancesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.dump.objectInstances.item collection
     * @param mt Unique identifier of the item
     * @returns a WithMtItemRequestBuilder
     */
    public byMt(mt: number) : WithMtItemRequestBuilder {
        if(!mt) throw new Error("mt cannot be undefined");
        const urlTplParams = getPathParameters(this.pathParameters);
        urlTplParams["mt"] = mt
        return new WithMtItemRequestBuilder(urlTplParams, this.requestAdapter);
    }
    /**
     * Instantiates a new ObjectInstancesRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/api/dump/object-instances", (x, y) => new ObjectInstancesRequestBuilder(x, y));
    }
}
/* tslint:enable */
/* eslint-enable */
